[tox]
skipsdist=True
envlist =
    drf{39,310,311,312,313,314,315,316},
    drfbuild{39,310,311,312,313,314,315,316},

[testenv]
deps =
    -r{toxinidir}/requirements-tox.txt

deps39 =
    django==2.2
    djangorestframework>=3.9,<3.10

deps310 =
    django==2.2
    djangorestframework>=3.10,<3.11

deps311 =
    django==3.2
    djangorestframework>=3.11,<3.12

deps312 =
    django==3.2
    djangorestframework>=3.12,<3.13

deps313 =
    django==4.0.4
    djangorestframework>=3.13,<3.14

deps314 =
    django==4.1.0
    djangorestframework>=3.14,<3.15

deps315 =
    django==5.2.5
    djangorestframework>=3.15,<3.16

deps316 =
    django==5.2.5
    djangorestframework>=3.16,<3.17

setenv =
    PYTHONPATH = {toxinidir}


# INDEX GENERATION

[index]
commands =
    fab index

[build]
commands =
    fab version

[testenv:drf39]
deps =
    {[testenv]deps}
    {[testenv]deps39}
commands =
    {[index]commands}

[testenv:drf310]
deps =
    {[testenv]deps}
    {[testenv]deps310}
commands =
    {[index]commands}

[testenv:drf311]
deps =
    {[testenv]deps}
    {[testenv]deps311}
commands =
    {[index]commands}

[testenv:drf312]
deps =
    {[testenv]deps}
    {[testenv]deps312}
commands =
    {[index]commands}

[testenv:drf313]
deps =
    {[testenv]deps}
    {[testenv]deps313}
commands =
    {[index]commands}

[testenv:drf314]
deps =
    {[testenv]deps}
    {[testenv]deps314}
commands =
    {[index]commands}

[testenv:drf315]
deps =
    {[testenv]deps}
    {[testenv]deps315}
commands =
    {[index]commands}

[testenv:drf316]
deps =
    {[testenv]deps}
    {[testenv]deps316}
commands =
    {[index]commands}

# SITE GENERATION

[testenv:drfbuild39]
deps =
    {[testenv:drf39]deps}
envdir =
    {toxworkdir}/drf39
commands =
    {[build]commands}

[testenv:drfbuild310]
deps =
    {[testenv:drf310]deps}
envdir =
    {toxworkdir}/drf310
commands =
    {[build]commands}

[testenv:drfbuild311]
deps =
    {[testenv:drf311]deps}
envdir =
    {toxworkdir}/drf311
commands =
    {[build]commands}

[testenv:drfbuild312]
deps =
    {[testenv:drf312]deps}
envdir =
    {toxworkdir}/drf312
commands =
    {[build]commands}

[testenv:drfbuild313]
deps =
    {[testenv:drf313]deps}
envdir =
    {toxworkdir}/drf313
commands =
    {[build]commands}

[testenv:drfbuild314]
deps =
    {[testenv:drf314]deps}
envdir =
    {toxworkdir}/drf314
commands =
    {[build]commands}

[testenv:drfbuild315]
deps =
    {[testenv:drf315]deps}
envdir =
    {toxworkdir}/drf315
commands =
    {[build]commands}

[testenv:drfbuild316]
deps =
    {[testenv:drf316]deps}
envdir =
    {toxworkdir}/drf316
commands =
    {[build]commands}
